FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    libboost-filesystem1.58.0 libboost-program-options1.58.0 \
    libboost-regex1.58.0 libboost-system1.58.0 libboost-thread1.58.0 \
    libboost-date-time1.58.0 libboost-iostreams1.58.0\
    libc6 libcurl3 libgcc1 liblog4cpp5v5  libproj9  \
    libstdc++6 libxml2 debconf dbconfig-common\
    apache2 libpq5 libapr1 gzip \
    libyajl2 libcurl3 

#WORKDIR /src 


#COPY .build/artifacts/* /usr

#RUN a2enconf mod_perl

#EXPOSE 80
#ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]

CMD ["/bin/bash"]
