FROM ubuntu:16.04

COPY /etc/apt/sources.list.d/metno.list /etc/apt/sources.list.d

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv 7423E2EB78589757 && \
	apt-get update && apt-get install -y \
	ca-certificates \
    libboost-filesystem1.58.0 libboost-program-options1.58.0 \
    libboost-regex1.58.0 libboost-system1.58.0 libboost-thread1.58.0 \
    libboost-date-time1.58.0 libboost-iostreams1.58.0\
    libc6 libcurl3 libgcc1 liblog4cpp5v5  libproj9  \
    libstdc++6 libpqxx-4.0 libxml2 debconf dbconfig-common less dialog\
    apache2 libpq5 libapr1 gzip \
    libyajl2 libcurl3 libmetlibs-pumet6 && \
    rm -rf /var/lib/apt/lists/*


COPY .runtime /
COPY etc/metno-wdb2ts/ /etc/metno-wdb2ts/
COPY runtime/entrypoint.sh /usr/bin
COPY etc/apache2/000-default.conf /etc/apache2/sites-available
COPY etc/apache2/envvars /etc/apache2
COPY etc/apache2/ports.conf /etc/apache2
COPY etc/apache2/metno-wdb2ts.load /etc/apache2/mods-available
COPY etc/apache2/mpm_worker.conf /etc/apache2/mods-available
COPY etc/apache2/metno-wdb2ts.conf /etc/apache2/conf-available

RUN mkdir -p /var/log/metno-wdb2ts && mkdir -p /var/lib/metno-wdb2ts/tmp

RUN chown -R www-data.www-data /var/log/metno-wdb2ts && \
 chown -R www-data.www-data /var/lib/metno-wdb2ts && \
 chown root.www-data /etc/metno-wdb2ts && \
 chmod g+rw /etc/metno-wdb2ts && \
 a2dismod mpm_event && a2enmod mpm_worker && a2enmod metno-wdb2ts && \
 a2enconf metno-wdb2ts && ldconfig

ENV PGHOST=localhost PGPORT=5432 APACHE_PORT=80 ETCD_HOSTS="http://localhost:2379" \
	ETCD_WDB2TS_PATH="/wdb2ts"

EXPOSE 80

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
