#!/bin/sh
### BEGIN INIT INFO
# Provides:          apache2-wdb2ts
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop apache2 web server (config /etc/apache2-wdb2ts)
### END INIT INFO

#
# this init script can be installed as /etc/init.d/apache2-wdb2ts
#

# source original init script to keep $0 and other arguments
. /etc/init.d/apache2
